# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 06:57
from __future__ import unicode_literals

import datetime
import django.core.files.storage
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pic',
            field=models.FileField(default='settings.MEDIA_ROOT/defaultcourse.jpg', storage=django.core.files.storage.FileSystemStorage(location=b'/home/jaley/coursehub/media'), upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 6, 57, 55, 455995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likeactivity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 6, 57, 55, 457604, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='settings.MEDIA_ROOT/default_profile.jpg', storage=django.core.files.storage.FileSystemStorage(location=b'/home/jaley/coursehub/media'), upload_to='logos'),
        ),
    ]
