# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 06:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190416_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 6, 58, 20, 988175, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likeactivity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 6, 58, 20, 989699, tzinfo=utc)),
        ),
    ]
