# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190413_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='like_courses',
            field=models.ManyToManyField(related_name='like_users', to='course.Course'),
        ),
    ]
