# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20190414_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='course.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='like_courses',
        ),
        migrations.AddField(
            model_name='likeactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='course.Profile', unique=True),
        ),
    ]
