# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 07:05
from __future__ import unicode_literals

import datetime
import django.core.files.storage
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20190416_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_pic',
            field=models.FileField(default='/home/jaley/coursehub/media/logos/defaultcourse.jpg', storage=django.core.files.storage.FileSystemStorage(location=b'/home/jaley/coursehub/media'), upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 7, 5, 50, 433619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likeactivity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 7, 5, 50, 435154, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='/home/jaley/coursehub/media/logos/default_profile.jpg', storage=django.core.files.storage.FileSystemStorage(location=b'/home/jaley/coursehub/media'), upload_to='logos'),
        ),
    ]
