# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 11:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0011_auto_20190416_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerprofile',
            name='profile_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='likeactivity',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='likeactivity',
            name='course',
        ),
        migrations.RemoveField(
            model_name='likeactivity',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 11, 29, 37, 510095, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='LearnerProfile',
        ),
        migrations.DeleteModel(
            name='LikeActivity',
        ),
    ]
